# Site settings
title: acthtml
email: acthtml[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  一个简单的前端程序员笔记本
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://acthtml.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
redcarpet:
    extensions: ["tables"]
